export { default as LeftColumn } from "./columns/LeftColumn.tsx"
export { default as RightColumn } from "./columns/RightColumn.tsx"
export { default as TopMain } from "./columns/TopMain.tsx"
export { default as MainColumn } from "./columns/MainColumn.tsx"
export { default as MainAboutColumn } from "./columns/MainAboutColumn.tsx"